export interface Member {
    member_id: number,
    member_name: string,
    member_code: string,
    account_no: string,
    registration_date: Date | null,
    suspension_date: Date | null,
    member_status_id: number | null,
    member_status_desc: string | null,
    num_of_vehicles: number | null,
    payment_warning: boolean | null,
    address?: string,
    zip_code: string | null,
    phone: string | null,
    sales_person_id: number | null,
    xero_contact_id: string | null,
    due_date_days: number | null,
    grace_period_length: number | null,
    auto_suspension: boolean,
    display_payment_warning: boolean,
    min_suspension_date: Date | null,
    apply_biaya_materai: boolean | null,
    va_bca: string | null,
    va_mandiri: string | null,
    apply_tax: boolean | null,
    faktur_pajak: boolean | null,
    nama_pajak: string | null,
    alamat_pajak: string | null,
    npwp: string | null,
    npkp: string | null,
    contact_person: string | null,
    mobile_phone: string | null,
    email: string | null,
    server_charge: number | null,
    notes: string | null,
    should_be_suspended: boolean | null,
}